title: Prince Cheruvathur
description: My projects and miscellaneous items
baseurl: "/about"
url: "https://prncher.github.io"
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one