title: Prince Cheruvathur
description: My projects and miscellaneous items
baseurl: "/about"
url: "https://prncher.github.io"
markdown: kramdown
theme: jekyll-theme-dinky
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one